---
name: Test url shorter
on: [pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.2'
          architecture: 'x64'
      - run: python -m pip install pytest flask yamllint
      - run: pytest
      - run: yamllint -c yamllint.conf .
      - run: echo "Todo ok!"
  search_vulns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: if egrep -R '^[pP]assword|[pP]ass|[pP]asswd|[kK]ey' *; then false; else true; fi
      - run: if grep -RP '(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])' *; then false; else true; fi
      - run: if grep -RP '(?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=])' *; then false; else true; fi
      - run: echo "Todo ok!"



