name: prueba1
on: [push]
jobs:
  prueba_action01:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9.2' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: pwd #python my_script.py
    - run: python -m pip install pytest flask
    - run: ls -ltr
    - run: grep -Ri pass
    - run: pytest
    - run: echo "creada la branch"